### ISSUE TITLE
docker-compose up -d失败：Service 'web' failed to build: The command '/bin/sh -c pip3 install --user -r /requirement.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com' returned a non-zero code: 1

### ISSUE THREAD

**Issue by tangboyy** [VKSRC/Github-Monitor#113]
执行docker-compose up -d时报错，我的docker版本为，docker-ce-20.10.6-3.el7.x86_64
   Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f9kncl7h/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ImportError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f9kncl7h/cryptography/
You are using pip version 8.1.1, however version 21.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip3 install --user -r /requirement.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com' returned a non-zero code: 1

**Comment by tangboyy** [comment]
python的pip版本已经更新到最新的 21.1.1 了，并不是 8.1.1，有没有大佬指点一下

**Comment by yinmin2020** [comment]
解决了吗？我也遇到了这个问题~

**Comment by TuuuNya** [comment]
参考 #115    这个方式应该能解决。
