### ISSUE TITLE
添加任务之后报错

### ISSUE THREAD

**Issue by Spr1ngBr0ther** [VKSRC/Github-Monitor#27]
401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
Traceback (most recent call last):
  File "/opt/Github-Monitor/server/github_monitor/apps/monitor/processors.py", line 67, in search_by_keyword_thread
    total = min(response.totalCount, 1000)
  File "/usr/local/python3Dir/lib/python3.6/site-packages/github/PaginatedList.py", line 155, in totalCount
    headers=self.__headers
  File "/usr/local/python3Dir/lib/python3.6/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/python3Dir/lib/python3.6/site-packages/github/Requester.py", line 275, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}

**Comment by AnYeMoWang** [comment]
@Spr1ngBr0ther 你添加的github token正确吗？是否进行过修改？

**Comment by Spr1ngBr0ther** [comment]
> @Spr1ngBr0ther 你添加的github token正确吗？是否进行过修改？

确认是正确的

**Comment by AnYeMoWang** [comment]
> > @Spr1ngBr0ther 你添加的github token正确吗？是否进行过修改？
> 
> 确认是正确的

你的微信或者QQ方便留一下么？我加你一下，看看具体是什么问题

**Comment by Spr1ngBr0ther** [comment]
> > > @Spr1ngBr0ther 你添加的github token正确吗？是否进行过修改？
> > 
> > 
> > 确认是正确的
> 
> 你的微信或者QQ方便留一下么？我加你一下，看看具体是什么问题

Q 964664831

**Comment by TuuuNya** [comment]
已解决，原因是添加了一个错误的Token，然后从MySQL中删除了错误的Token并添加了正确的Token，但是程序会从Redis里面取Token，所以一直取的是错误的Token，所以报错。
