### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 49: illegal multibyte sequence

### ISSUE THREAD

**Issue by jiluhu** [VKSRC/Github-Monitor#41]
(env) D:\zxdf\Workspaces\myworkspace\Github-Monitor\server>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\django\core\management\__init__.py", line 371, in execute_fro
m_command_line
    utility.execute()
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\django\core\management\__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\django\conf\__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\github_monitor\settings.py", line 18, in <module>
    load_dotenv(dotenv_path=os.path.join(BASE_DIR, '..', '.env'), override=True)
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\dotenv\main.py", line 309, in load_dotenv
    return DotEnv(f, verbose=verbose).set_as_environment_variables(override=override)
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\dotenv\main.py", line 129, in set_as_environment_variables
    for k, v in self.dict().items():
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\dotenv\main.py", line 115, in dict
    values = OrderedDict(self.parse())
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\dotenv\main.py", line 121, in parse
    for mapping in parse_stream(stream):
  File "D:\zxdf\Workspaces\myworkspace\Github-Monitor\server\env\lib\site-packages\dotenv\main.py", line 83, in parse_stream
    string = stream.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 49: illegal multibyte sequence

(env) D:\zxdf\Workspaces\myworkspace\Github-Monitor\server>

**Comment by AnYeMoWang** [comment]
你把.env文件转成utf8编码格式试试，应该是你windows的编辑器默认是gbk编码的。
