### ISSUE TITLE
根据官方镜像部署报错

### ISSUE THREAD

**Issue by jesse-tang** [VKSRC/Github-Monitor#61]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/docker/Github-Monitor/server/github_monitor/apps/monitor/processors.py", line 63, in search_by_keyword_thread
    session, _token = self._new_session()
  File "/home/docker/Github-Monitor/server/github_monitor/apps/monitor/processors.py", line 51, in _new_session
    token = self.get_available_token()
  File "/home/docker/Github-Monitor/server/github_monitor/apps/monitor/processors.py", line 41, in get_available_token
    key = key.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 0: invalid start byte

**Comment by AnYeMoWang** [comment]
@jesse-tang 你是用docker部署的吗？Redis用的是镜像自带的redis，还是自己配置的redis？
