### ISSUE TITLE
GitHub api 超时

### ISSUE THREAD

**Issue by w2n1ck** [VKSRC/Github-Monitor#82]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/biyidong/Github-Monitor/server/github_monitor/apps/monitor/processors.py", line 98, in search_by_keyword_thread
    self.process_pages(page_content, keyword)
  File "/home/biyidong/Github-Monitor/server/github_monitor/apps/monitor/processors.py", line 170, in process_pages
    data = get_data(_file)
  File "/home/biyidong/Github-Monitor/server/github_monitor/apps/monitor/processors.py", line 106, in get_data
    github_file.update()
  File "/usr/local/python3/lib/python3.7/site-packages/github/GithubObject.py", line 291, in update
    headers=conditionalRequestHeader
  File "/usr/local/python3/lib/python3.7/site-packages/github/Requester.py", line 324, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/python3/lib/python3.7/site-packages/github/Requester.py", line 377, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/python3/lib/python3.7/site-packages/github/Requester.py", line 401, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/python3/lib/python3.7/site-packages/github/Requester.py", line 109, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_redirects=False)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 685, in send
    r.content
  File "/usr/local/python3/lib/python3.7/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/python3/lib/python3.7/site-packages/requests/models.py", line 758, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out.

**Comment by w2n1ck** [comment]
![image](https://user-images.githubusercontent.com/26704158/87895055-09a5c800-ca77-11ea-8d45-167db62932ba.png)

token全部正常，启动什么的都正常，就是无任务结果

**Comment by w2n1ck** [comment]
入库有些问题，已解决
